const data = {
  '5501M': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5501M',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '0',
    'manufacturer-code': 'IX',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '21.45',
    cdpmq: '33.53',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '34.83',
    bioequivalence: 'a',
    'brand-name': 'XOROX',
    'mp-pt': 'aciclovir',
    'tpuu-or-mpp-pt': 'aciclovir 3% eye ointment, 4.5 g',
    'indication-id': '5964',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Herpes simplex keratitis',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01AD03',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5504Q': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5504Q',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': '',
    mq: '3',
    repeats: '5',
    'manufacturer-code': 'UO',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '8.60',
    cdpmq: '37.87',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '39.17',
    bioequivalence: '',
    'brand-name': 'Viscotears Gel PF',
    'mp-pt': 'carbomer-980',
    'tpuu-or-mpp-pt': 'carbomer-980 0.2% eye drops, 30 x 0.6 mL unit doses',
    'indication-id': '6172',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Severe dry eye syndrome Clinical criteria: * Patient must be sensitive to preservatives in multi-dose eye drops.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5502N': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5502N',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': '',
    mq: '3',
    repeats: '5',
    'manufacturer-code': 'AQ',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '6.98',
    cdpmq: '33.01',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '34.31',
    bioequivalence: '',
    'brand-name': 'Poly Gel',
    'mp-pt': 'carbomer-974P',
    'tpuu-or-mpp-pt': 'carbomer-974P 0.3% eye gel, 30 x 500 mg unit doses',
    'indication-id': '6172',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Severe dry eye syndrome Clinical criteria: * Patient must be sensitive to preservatives in multi-dose eye drops.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5503P': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5503P',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'UO',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '3.64',
    'therapeutic-premium': '0.00',
    cp2p: '3.03',
    cdpmq: '15.11',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '6.67',
    mdpmq: '18.75',
    mrvsn: '16.41',
    bioequivalence: 'a',
    'brand-name': 'Viscotears',
    'mp-pt': 'carbomer-980',
    'tpuu-or-mpp-pt': 'carbomer-980 0.2% eye gel, 10 g',
    'indication-id': '6153',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: "Severe dry eye syndrome, including Sjogren's syndrome",
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5544T': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5544T',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '4.76',
    'therapeutic-premium': '0.00',
    cp2p: '7.26',
    cdpmq: '19.34',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '12.02',
    mdpmq: '24.10',
    mrvsn: '20.64',
    bioequivalence: 'a',
    'brand-name': 'Betoptic',
    'mp-pt': 'betaxolol',
    'tpuu-or-mpp-pt': 'betaxolol 0.5% eye drops, 5 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01ED02',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5564W': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5564W',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': '',
    mq: '2',
    repeats: '0',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '4.36',
    'therapeutic-premium': '0.00',
    cp2p: '9.59',
    cdpmq: '31.26',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '11.77',
    mdpmq: '35.62',
    mrvsn: '32.56',
    bioequivalence: 'a',
    'brand-name': 'Ciloxan',
    'mp-pt': 'ciprofloxacin',
    'tpuu-or-mpp-pt': 'ciprofloxacin 0.3% eye drops, 5 mL',
    'indication-id': '4181',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Bacterial keratitis Treatment criteria: * Must be treated by an ophthalmologist or in consultation with an ophthalmologist.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01AE03',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5565X': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5565X',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '0',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '16.03',
    cdpmq: '28.11',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '29.41',
    bioequivalence: '',
    'brand-name': 'Maxidex',
    'mp-pt': 'dexamethasone',
    'tpuu-or-mpp-pt': 'dexamethasone 0.1% eye drops, 5 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '13615', '13290', '0',
      '0',     '0',     '0',
      '0',     '0',     '0',
      '0',     '0',     '0',
      '0',     '0',     '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01BA01',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5513E': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5513E',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '0',
    'manufacturer-code': 'AG',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '3.16',
    cdpmq: '15.24',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '16.54',
    bioequivalence: '',
    'brand-name': 'FML Liquifilm',
    'mp-pt': 'fluorometholone',
    'tpuu-or-mpp-pt': 'fluorometholone 0.1% eye drops, 5 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '13615', '13290', '0',
      '0',     '0',     '0',
      '0',     '0',     '0',
      '0',     '0',     '0',
      '0',     '0',     '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01BA07',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5533F': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5533F',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '0',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '3.16',
    cdpmq: '15.24',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '16.54',
    bioequivalence: '',
    'brand-name': 'Flarex',
    'mp-pt': 'fluorometholone acetate',
    'tpuu-or-mpp-pt': 'fluorometholone acetate 0.1% eye drops, 5 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '13615', '13290', '0',
      '0',     '0',     '0',
      '0',     '0',     '0',
      '0',     '0',     '0',
      '0',     '0',     '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01BA07',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5557L': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5557L',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '2',
    'manufacturer-code': 'SW',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '3.26',
    cdpmq: '15.34',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '16.64',
    bioequivalence: '',
    'brand-name': 'Soframycin',
    'mp-pt': 'framycetin sulfate',
    'tpuu-or-mpp-pt': 'framycetin sulfate 0.5% eye/ear drops, 8 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S03AA',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5566Y': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5566Y',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '2',
    'manufacturer-code': 'AG',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '10.32',
    cdpmq: '22.40',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '23.70',
    bioequivalence: '',
    'brand-name': 'Genoptic',
    'mp-pt': 'gentamicin',
    'tpuu-or-mpp-pt': 'gentamicin 0.3% eye drops, 5 mL',
    'indication-id': '5477',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Suspected Pseudomonal eye infection',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01AA11',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5516H': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5516H',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '0',
    'manufacturer-code': 'AS',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '5.48',
    cdpmq: '17.56',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '18.86',
    bioequivalence: '',
    'brand-name': 'Hycor',
    'mp-pt': 'hydrocortisone acetate',
    'tpuu-or-mpp-pt': 'hydrocortisone acetate 1% eye ointment, 5 g',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '13615', '13290', '0',
      '0',     '0',     '0',
      '0',     '0',     '0',
      '0',     '0',     '0',
      '0',     '0',     '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01BA02',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5517J': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5517J',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'AF',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '3.53',
    cdpmq: '15.61',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '16.91',
    bioequivalence: '',
    'brand-name': 'Methopt',
    'mp-pt': 'hypromellose',
    'tpuu-or-mpp-pt': 'hypromellose 0.5% eye drops, 15 mL',
    'indication-id': '6120',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: "Severe dry eye syndrome, including Sjogren's syndrome",
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5520M': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5520M',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'IQ',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '3.70',
    cdpmq: '15.78',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '17.08',
    bioequivalence: 'a',
    'brand-name': 'Poly-Tears',
    'mp-pt': 'dextran-70 + hypromellose',
    'tpuu-or-mpp-pt': 'dextran-70 0.1% + hypromellose 0.3% eye drops, 15 mL',
    'indication-id': '6120',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: "Severe dry eye syndrome, including Sjogren's syndrome",
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5521N': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5521N',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': '',
    mq: '3',
    repeats: '5',
    'manufacturer-code': 'AQ',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '8.30',
    cdpmq: '36.97',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '38.27',
    bioequivalence: '',
    'brand-name': 'Bion Tears',
    'mp-pt': 'dextran-70 + hypromellose',
    'tpuu-or-mpp-pt': 'dextran-70 0.1% + hypromellose 0.3% eye drops, 28 x 0.4 mL unit doses',
    'indication-id': '6172',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Severe dry eye syndrome Clinical criteria: * Patient must be sensitive to preservatives in multi-dose eye drops.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5523Q': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5523Q',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': '',
    mq: '2',
    repeats: '5',
    'manufacturer-code': 'IQ',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '6.44',
    cdpmq: '24.96',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '26.26',
    bioequivalence: '',
    'brand-name': 'Poly Visc',
    'mp-pt': 'paraffin',
    'tpuu-or-mpp-pt': 'paraffin 1 g/g eye ointment, 3.5 g',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5536J': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5536J',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '5.35',
    cdpmq: '17.43',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '18.73',
    bioequivalence: '',
    'brand-name': 'Isopto Carpine',
    'mp-pt': 'pilocarpine',
    'tpuu-or-mpp-pt': 'pilocarpine hydrochloride 1% eye drops, 15 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01EB01',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5537K': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5537K',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '6.40',
    cdpmq: '18.48',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '19.78',
    bioequivalence: '',
    'brand-name': 'Isopto Carpine',
    'mp-pt': 'pilocarpine',
    'tpuu-or-mpp-pt': 'pilocarpine hydrochloride 2% eye drops, 15 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01EB01',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5538L': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5538L',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '8.88',
    cdpmq: '20.96',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '22.26',
    bioequivalence: '',
    'brand-name': 'Isopto Carpine',
    'mp-pt': 'pilocarpine',
    'tpuu-or-mpp-pt': 'pilocarpine hydrochloride 4% eye drops, 15 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01EB01',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5568C': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5568C',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '0',
    'manufacturer-code': 'AG',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '16.87',
    cdpmq: '28.95',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '30.25',
    bioequivalence: '',
    'brand-name': 'Prednefrin Forte',
    'mp-pt': 'prednisolone acetate + phenylephrine',
    'tpuu-or-mpp-pt': 'prednisolone acetate 1% + phenylephrine hydrochloride 0.12% eye drops, 10 mL',
    'indication-id': '6087',
    'increase-code': '3',
    'note-ids': [
      '7606', '7607', '0',
      '0',    '0',    '0',
      '0',    '0',    '0',
      '0',    '0',    '0',
      '0',    '0',    '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Uveitis',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01BB02',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5550D': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5550D',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'MF',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '5.79',
    cdpmq: '17.87',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '19.17',
    bioequivalence: '',
    'brand-name': 'Timoptol XE',
    'mp-pt': 'timolol',
    'tpuu-or-mpp-pt': 'timolol 0.5% eye drops, 2.5 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01ED01',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5548B': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5548B',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'MF',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '5.73',
    cdpmq: '17.81',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '19.11',
    bioequivalence: '',
    'brand-name': 'Timoptol',
    'mp-pt': 'timolol',
    'tpuu-or-mpp-pt': 'timolol 0.5% eye drops, 5 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01ED01',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5569D': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5569D',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '2',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '10.62',
    cdpmq: '22.70',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '24.00',
    bioequivalence: '',
    'brand-name': 'Tobrex',
    'mp-pt': 'tobramycin',
    'tpuu-or-mpp-pt': 'tobramycin 0.3% eye drops, 5 mL',
    'indication-id': '5477',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Suspected Pseudomonal eye infection',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01AA12',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5570E': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5570E',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '0',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '13.18',
    cdpmq: '25.26',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '26.56',
    bioequivalence: '',
    'brand-name': 'Tobrex',
    'mp-pt': 'tobramycin',
    'tpuu-or-mpp-pt': 'tobramycin 0.3% eye ointment, 3.5 g',
    'indication-id': '5477',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Suspected Pseudomonal eye infection',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01AA12',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5508X': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5508X',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'AG',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '3.15',
    cdpmq: '15.23',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '16.53',
    bioequivalence: '',
    'brand-name': 'Refresh Liquigel',
    'mp-pt': 'carmellose sodium',
    'tpuu-or-mpp-pt': 'carmellose sodium 1% eye drops, 15 mL',
    'indication-id': '6120',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: "Severe dry eye syndrome, including Sjogren's syndrome",
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5505R': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5505R',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': '',
    mq: '3',
    repeats: '5',
    'manufacturer-code': 'PP',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '5.86',
    cdpmq: '29.65',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '30.95',
    bioequivalence: 'a',
    'brand-name': 'Optifresh Plus',
    'mp-pt': 'carmellose sodium',
    'tpuu-or-mpp-pt': 'carmellose sodium 1% eye drops, 30 x 0.4 mL unit doses',
    'indication-id': '6172',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Severe dry eye syndrome Clinical criteria: * Patient must be sensitive to preservatives in multi-dose eye drops.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5507W': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5507W',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'AG',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '3.15',
    cdpmq: '15.23',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '16.53',
    bioequivalence: '',
    'brand-name': 'Refresh Tears Plus',
    'mp-pt': 'carmellose sodium',
    'tpuu-or-mpp-pt': 'carmellose sodium 0.5% eye drops, 15 mL',
    'indication-id': '6120',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: "Severe dry eye syndrome, including Sjogren's syndrome",
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5506T': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5506T',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': '',
    mq: '3',
    repeats: '5',
    'manufacturer-code': 'PP',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '5.86',
    cdpmq: '29.65',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '30.95',
    bioequivalence: 'a',
    'brand-name': 'Optifresh Tears',
    'mp-pt': 'carmellose sodium',
    'tpuu-or-mpp-pt': 'carmellose sodium 0.5% eye drops, 30 x 0.4 mL unit doses',
    'indication-id': '6172',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Severe dry eye syndrome Clinical criteria: * Patient must be sensitive to preservatives in multi-dose eye drops.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5567B': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5567B',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': '',
    mq: '2',
    repeats: '0',
    'manufacturer-code': 'AG',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '10.20',
    cdpmq: '32.48',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '33.78',
    bioequivalence: '',
    'brand-name': 'Ocuflox',
    'mp-pt': 'ofloxacin',
    'tpuu-or-mpp-pt': 'ofloxacin 0.3% eye drops, 5 mL',
    'indication-id': '4181',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Bacterial keratitis Treatment criteria: * Must be treated by an ophthalmologist or in consultation with an ophthalmologist.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01AE01',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5552F': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5552F',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'TX',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '5.83',
    cdpmq: '17.91',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '19.21',
    bioequivalence: 'a',
    'brand-name': 'APO-Latanoprost',
    'mp-pt': 'latanoprost',
    'tpuu-or-mpp-pt': 'latanoprost 0.005% eye drops, 2.5 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01EE01',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5563T': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5563T',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'AG',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '11.93',
    cdpmq: '24.01',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '25.31',
    bioequivalence: '',
    'brand-name': 'Alphagan P 1.5',
    'mp-pt': 'brimonidine',
    'tpuu-or-mpp-pt': 'brimonidine tartrate 0.15% eye drops, 5 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01EA05',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5534G': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5534G',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'PE',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '11.93',
    cdpmq: '24.01',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '25.31',
    bioequivalence: 'a',
    'brand-name': 'Enidin',
    'mp-pt': 'brimonidine',
    'tpuu-or-mpp-pt': 'brimonidine tartrate 0.2% eye drops, 5 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01EA05',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5540N': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5540N',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '4.78',
    'therapeutic-premium': '0.00',
    cp2p: '14.22',
    cdpmq: '26.30',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '19.00',
    mdpmq: '31.08',
    mrvsn: '27.60',
    bioequivalence: 'a',
    'brand-name': 'Azopt',
    'mp-pt': 'brinzolamide',
    'tpuu-or-mpp-pt': 'brinzolamide 1% eye drops, 5 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01EC04',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5519L': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5519L',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'IQ',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '3.53',
    cdpmq: '15.61',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '16.91',
    bioequivalence: 'a',
    'brand-name': 'HPMC PAA',
    'mp-pt': 'hypromellose + carbomer-980',
    'tpuu-or-mpp-pt': 'hypromellose 0.3% + carbomer-980 0.2% eye gel, 10 g',
    'indication-id': '6120',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: "Severe dry eye syndrome, including Sjogren's syndrome",
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5542Q': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5542Q',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'TX',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '10.59',
    cdpmq: '22.67',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '23.97',
    bioequivalence: 'a',
    'brand-name': 'APO-Dorzolamide/Timolol 20/5',
    'mp-pt': 'dorzolamide + timolol',
    'tpuu-or-mpp-pt': 'dorzolamide 2% + timolol 0.5% eye drops, 5 mL',
    'indication-id': '5038',
    'increase-code': '2',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Elevated intra-ocular pressure Clinical criteria: * The condition must have been inadequately controlled with monotherapy, AND * Patient must have open-angle glaucoma; OR * Patient must have ocular hypertension.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01EC',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5554H': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5554H',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '25.36',
    cdpmq: '37.44',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '38.74',
    bioequivalence: '',
    'brand-name': 'Travatan',
    'mp-pt': 'travoprost',
    'tpuu-or-mpp-pt': 'travoprost 0.004% eye drops, 2.5 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01EE04',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5553G': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5553G',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'TX',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '10.28',
    cdpmq: '22.36',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '23.66',
    bioequivalence: 'a',
    'brand-name': 'APO-Latanoprost/Timolol 0.05/5',
    'mp-pt': 'latanoprost + timolol',
    'tpuu-or-mpp-pt': 'latanoprost 0.005% + timolol 0.5% eye drops, 2.5 mL',
    'indication-id': '5038',
    'increase-code': '2',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Elevated intra-ocular pressure Clinical criteria: * The condition must have been inadequately controlled with monotherapy, AND * Patient must have open-angle glaucoma; OR * Patient must have ocular hypertension.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01EE',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5551E': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5551E',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'TY',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '24.92',
    cdpmq: '37.00',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '38.30',
    bioequivalence: 'a',
    'brand-name': 'Bimprozt',
    'mp-pt': 'bimatoprost',
    'tpuu-or-mpp-pt': 'bimatoprost 0.03% eye drops, 3 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01EE03',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5524R': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5524R',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'AQ',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '3.16',
    cdpmq: '15.24',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '16.54',
    bioequivalence: '',
    'brand-name': 'Systane',
    'mp-pt': 'polyethylene glycol-400 + propylene glycol',
    'tpuu-or-mpp-pt': 'polyethylene glycol-400 0.4% + propylene glycol 0.3% eye drops, 15 mL',
    'indication-id': '6120',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: "Severe dry eye syndrome, including Sjogren's syndrome",
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5535H': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5535H',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'AG',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '17.05',
    cdpmq: '29.13',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '30.43',
    bioequivalence: '',
    'brand-name': 'Combigan',
    'mp-pt': 'brimonidine + timolol',
    'tpuu-or-mpp-pt': 'brimonidine tartrate 0.2% + timolol 0.5% eye drops, 5 mL',
    'indication-id': '5038',
    'increase-code': '2',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Elevated intra-ocular pressure Clinical criteria: * The condition must have been inadequately controlled with monotherapy, AND * Patient must have open-angle glaucoma; OR * Patient must have ocular hypertension.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01EA',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5555J': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5555J',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '29.82',
    cdpmq: '41.90',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '41.30',
    bioequivalence: '',
    'brand-name': 'Duotrav',
    'mp-pt': 'travoprost + timolol',
    'tpuu-or-mpp-pt': 'travoprost 0.004% + timolol 0.5% eye drops, 2.5 mL',
    'indication-id': '5038',
    'increase-code': '2',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Elevated intra-ocular pressure Clinical criteria: * The condition must have been inadequately controlled with monotherapy, AND * Patient must have open-angle glaucoma; OR * Patient must have ocular hypertension.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01EE',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5556K': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5556K',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '3',
    'manufacturer-code': 'AG',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '3.15',
    cdpmq: '15.23',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '16.53',
    bioequivalence: '',
    'brand-name': 'Optive',
    'mp-pt': 'carmellose sodium + glycerol',
    'tpuu-or-mpp-pt': 'carmellose sodium 0.5% + glycerol 0.9% eye drops, 15 mL',
    'indication-id': '6097',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: "Severe dry eye syndrome, including Sjogren's syndrome",
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5545W': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5545W',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': '',
    mq: '2',
    repeats: '5',
    'manufacturer-code': 'RB',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '11.02',
    cdpmq: '34.12',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '35.42',
    bioequivalence: '',
    'brand-name': 'tearsagain',
    'mp-pt': 'soy lecithin + tocopherol + vitamin A',
    'tpuu-or-mpp-pt': 'soy lecithin 1% + tocopherol 0.002% + vitamin A palmitate 0.025% spray, 100 actuations',
    'indication-id': '6172',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Severe dry eye syndrome Clinical criteria: * Patient must be sensitive to preservatives in multi-dose eye drops.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5558M': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5558M',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'AG',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '29.37',
    cdpmq: '41.45',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '41.30',
    bioequivalence: '',
    'brand-name': 'Ganfort 0.3/5',
    'mp-pt': 'bimatoprost + timolol',
    'tpuu-or-mpp-pt': 'bimatoprost 0.03% + timolol 0.5% eye drops, 3 mL',
    'indication-id': '5038',
    'increase-code': '2',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Elevated intra-ocular pressure Clinical criteria: * The condition must have been inadequately controlled with monotherapy, AND * Patient must have open-angle glaucoma; OR * Patient must have ocular hypertension.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01EE',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5562R': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5562R',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '17.79',
    cdpmq: '29.87',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '31.17',
    bioequivalence: '',
    'brand-name': 'Azarga',
    'mp-pt': 'brinzolamide + timolol',
    'tpuu-or-mpp-pt': 'brinzolamide 1% + timolol 0.5% eye drops, 5 mL',
    'indication-id': '5038',
    'increase-code': '2',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Elevated intra-ocular pressure Clinical criteria: * The condition must have been inadequately controlled with monotherapy, AND * Patient must have open-angle glaucoma; OR * Patient must have ocular hypertension.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01EC54',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5522P': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5522P',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'PE',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '12.33',
    cdpmq: '24.41',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '25.71',
    bioequivalence: 'a',
    'brand-name': 'Ircal',
    'mp-pt': 'paraffin',
    'tpuu-or-mpp-pt': 'paraffin 1 g/g eye ointment, 2 x 3.5 g',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5532E': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5532E',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': '',
    mq: '2',
    repeats: '5',
    'manufacturer-code': 'AQ',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '9.77',
    cdpmq: '31.62',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '32.92',
    bioequivalence: '',
    'brand-name': 'Systane',
    'mp-pt': 'polyethylene glycol-400 + propylene glycol',
    'tpuu-or-mpp-pt': 'polyethylene glycol-400 0.4% + propylene glycol 0.3% eye drops, 28 x 0.8 mL unit doses',
    'indication-id': '6172',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Severe dry eye syndrome Clinical criteria: * Patient must be sensitive to preservatives in multi-dose eye drops.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5541P': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5541P',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'TX',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '7.85',
    cdpmq: '19.93',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '21.23',
    bioequivalence: 'a',
    'brand-name': 'APO-Dorzolamide',
    'mp-pt': 'dorzolamide',
    'tpuu-or-mpp-pt': 'dorzolamide 2% eye drops, 5 mL',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01EC03',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '5526W': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '5526W',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'PE',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '3.53',
    cdpmq: '15.61',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '16.91',
    bioequivalence: 'a',
    'brand-name': 'PVA Tears',
    'mp-pt': 'polyvinyl alcohol',
    'tpuu-or-mpp-pt': 'polyvinyl alcohol 1.4% eye drops, 15 mL',
    'indication-id': '6120',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: "Severe dry eye syndrome, including Sjogren's syndrome",
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '2184Y': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '2184Y',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'AE',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '22.47',
    cdpmq: '34.55',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '35.85',
    bioequivalence: '',
    'brand-name': 'Hylo-Fresh',
    'mp-pt': 'hyaluronate sodium',
    'tpuu-or-mpp-pt': 'hyaluronate sodium 0.1% eye drops, 10 mL',
    'indication-id': '4105',
    'increase-code': '2',
    'note-ids': [
      '7873', '0', '0',
      '0',    '0', '0',
      '0',    '0', '0',
      '0',    '0', '0',
      '0',    '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Severe dry eye syndrome Clinical criteria: * Patient must be sensitive to preservatives in multi-dose eye drops.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '2171G': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '2171G',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'AE',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '22.47',
    cdpmq: '34.55',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '35.85',
    bioequivalence: '',
    'brand-name': 'Hylo-Forte',
    'mp-pt': 'hyaluronate sodium',
    'tpuu-or-mpp-pt': 'hyaluronate sodium 0.2% eye drops, 10 mL',
    'indication-id': '4105',
    'increase-code': '2',
    'note-ids': [
      '7873', '0', '0',
      '0',    '0', '0',
      '0',    '0', '0',
      '0',    '0', '0',
      '0',    '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Severe dry eye syndrome Clinical criteria: * Patient must be sensitive to preservatives in multi-dose eye drops.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '2167C': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '2167C',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '2',
    repeats: '5',
    'manufacturer-code': 'AE',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '6.44',
    cdpmq: '24.96',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '26.26',
    bioequivalence: '',
    'brand-name': 'VitA-POS',
    'mp-pt': 'retinol palmitate + paraffin',
    'tpuu-or-mpp-pt': 'retinol palmitate 0.0138% + paraffin eye ointment, 5 g',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '8019', '0', '0',
      '0',    '0', '0',
      '0',    '0', '0',
      '0',    '0', '0',
      '0',    '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '2748P': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '2748P',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'MF',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '22.63',
    cdpmq: '34.71',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '36.01',
    bioequivalence: '',
    'brand-name': 'Saflutan',
    'mp-pt': 'tafluprost',
    'tpuu-or-mpp-pt': 'tafluprost 0.0015% eye drops, 30 x 0.3 mL unit doses',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01EE05',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '10053D': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '10053D',
    'restriction-flag': 'U',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'AG',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '20.92',
    cdpmq: '33.00',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '34.30',
    bioequivalence: '',
    'brand-name': 'Lumigan PF',
    'mp-pt': 'bimatoprost',
    'tpuu-or-mpp-pt': 'bimatoprost 0.03% eye drops, 30 x 0.4 mL unit doses',
    'indication-id': '',
    'increase-code': '',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {},
    atc: 'S01EE03',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '10108B': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '10108B',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'AG',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '25.71',
    cdpmq: '37.79',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '39.09',
    bioequivalence: '',
    'brand-name': 'GANfort PF 0.3/5',
    'mp-pt': 'bimatoprost + timolol',
    'tpuu-or-mpp-pt': 'bimatoprost 0.03% + timolol 0.5% eye drops, 30 x 0.4 mL unit doses',
    'indication-id': '5038',
    'increase-code': '2',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Elevated intra-ocular pressure Clinical criteria: * The condition must have been inadequately controlled with monotherapy, AND * Patient must have open-angle glaucoma; OR * Patient must have ocular hypertension.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01EE',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '11112W': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '11112W',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '2',
    'manufacturer-code': 'AS',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '4.11',
    cdpmq: '16.19',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '17.49',
    bioequivalence: '',
    'brand-name': 'Chlorsig',
    'mp-pt': 'chloramphenicol',
    'tpuu-or-mpp-pt': 'chloramphenicol 0.5% eye drops, 10 mL',
    'indication-id': '5835',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'For treatment of a patient identifying as Aboriginal or Torres Strait Islander',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01AA01',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '10547D': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '10547D',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'NV',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '16.56',
    cdpmq: '28.64',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '29.94',
    bioequivalence: '',
    'brand-name': 'Simbrinza 1%/0.2%',
    'mp-pt': 'brinzolamide + brimonidine',
    'tpuu-or-mpp-pt': 'brinzolamide 1% + brimonidine tartrate 0.2% eye drops, 5 mL',
    'indication-id': '5038',
    'increase-code': '2',
    'note-ids': [
      '14807', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Elevated intra-ocular pressure Clinical criteria: * The condition must have been inadequately controlled with monotherapy, AND * Patient must have open-angle glaucoma; OR * Patient must have ocular hypertension.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01EC54',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '11439C': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '11439C',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'AE',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '21.50',
    cdpmq: '33.58',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '34.88',
    bioequivalence: '',
    'brand-name': 'Novatears',
    'mp-pt': 'perfluorohexyloctane',
    'tpuu-or-mpp-pt': 'perfluorohexyloctane 100% eye drops, 3 mL',
    'indication-id': '6172',
    'increase-code': '2',
    'note-ids': [
      '21971', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Severe dry eye syndrome Clinical criteria: * Patient must be sensitive to preservatives in multi-dose eye drops.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '11634H': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '11634H',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': '',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'IQ',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '2.49',
    cdpmq: '14.57',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '15.87',
    bioequivalence: 'a',
    'brand-name': 'In a Wink Moisturising',
    'mp-pt': 'hypromellose',
    'tpuu-or-mpp-pt': 'hypromellose 0.3% w/w eye drops, 10 mL',
    'indication-id': '6120',
    'increase-code': '2',
    'note-ids': [
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0', '0',
      '0', '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: "Severe dry eye syndrome, including Sjogren's syndrome",
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '11853W': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '11853W',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'CX',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '18.28',
    cdpmq: '30.36',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '31.66',
    bioequivalence: '',
    'brand-name': 'Evolve Carmellose',
    'mp-pt': 'carmellose sodium',
    'tpuu-or-mpp-pt': 'carmellose sodium 0.5% eye drops, 10 mL',
    'indication-id': '6172',
    'increase-code': '2',
    'note-ids': [
      '22372', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Severe dry eye syndrome Clinical criteria: * Patient must be sensitive to preservatives in multi-dose eye drops.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '11849P': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '11849P',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'CX',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '18.28',
    cdpmq: '30.36',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '31.66',
    bioequivalence: '',
    'brand-name': 'Evolve Hypromellose',
    'mp-pt': 'hypromellose',
    'tpuu-or-mpp-pt': 'hypromellose 0.3% w/v eye drops, 10 mL',
    'indication-id': '6172',
    'increase-code': '2',
    'note-ids': [
      '22372', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Severe dry eye syndrome Clinical criteria: * Patient must be sensitive to preservatives in multi-dose eye drops.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '12612T': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '12612T',
    'restriction-flag': 'A',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'CS',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '25.59',
    cdpmq: '37.67',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '38.97',
    bioequivalence: '',
    'brand-name': 'Cationorm',
    'mp-pt': 'liquid paraffin + glycerol + tyloxapol + poloxamer-188 + trometamol hydrochlorid',
    'tpuu-or-mpp-pt': 'liquid paraffin + glycerol + tyloxapol + poloxamer-188 + trometamol hydrochloride + trometamol + cetalkonium chloride eye drops, 10 mL',
    'indication-id': '6172',
    'increase-code': '2',
    'note-ids': [
      '26237', '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0',
      '0',     '0', '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Severe dry eye syndrome Clinical criteria: * Patient must be sensitive to preservatives in multi-dose eye drops.',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA20',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  },
  '12663L': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '12663L',
    'restriction-flag': 'A',
    'has-caution': 'C',
    'has-note': 'N',
    mq: '1',
    repeats: '5',
    'manufacturer-code': 'CS',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '69.89',
    cdpmq: '81.97',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '41.30',
    bioequivalence: '',
    'brand-name': 'Ikervis',
    'mp-pt': 'ciclosporin',
    'tpuu-or-mpp-pt': 'ciclosporin 0.1% eye drops, 30 x 0.3 mL unit doses',
    'indication-id': '12284',
    'increase-code': '2',
    'note-ids': [
      '27773', '27774', '25796',
      '0',     '0',     '0',
      '0',     '0',     '0',
      '0',     '0',     '0',
      '0',     '0',     '0'
    ],
    caution_ids: [],
    indications: {
      description: "Chronic severe dry eye disease with keratitis Treatment Phase: Continuing treatment Clinical criteria: * Patient must have received PBS-subsidised treatment with this drug for this condition, AND * The condition must have improved to an extent that corneal fluorescein staining, using the same scale used at the time of the first authority application, shows an improvement (reduction) by at least 3 grades from baseline (the grade stated in the first authority application) - the improvement need only be demonstrated by staining once only with the first Continuing treatment authority application, AND * The condition must have improved to an extent that the patient's ocular surface disease index score at the time of this authority application, has improved (reduced) by at least 30% compared to the value stated in the first authority application (i.e. baseline). Treatment criteria: * Must be treated by an ophthalmologist or by an accredited ophthalmology registrar in consultation with an ophthalmologist; OR * Must be treated by an optometrist in accordance with Optometry Board of Australia guidelines. Prescribing instructions: State in the first continuing treatment authority application for this drug: (i) an improved corneal fluorescein staining grade (a numerical value that has improved by 3 grades from that provided in the first Initial 1 treatment authority application). State in all continuing treatment authority applications: (ii) the ocular surface disease index score at the time of this authority application (a numerical value that is at least 30% lower than that stated in the first Initial 1 treatment authority application).",
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01XA18',
    'caution-ids': [ '27780', '0', '0', '0', '0' ]
  },
  '12572Q': {
    'program-code': 'GE',
    'atc-level-code': '',
    'atc-type': 'P',
    'atc-print-option': '1',
    'item-code': '12572Q',
    'restriction-flag': 'R',
    'has-caution': '',
    'has-note': 'N',
    mq: '1',
    repeats: '0',
    'manufacturer-code': 'AG',
    'pack-size': '1',
    'markup-band': 'C',
    'fee-code': 'RP',
    'dangerous-drug-code': '',
    'brand-premium': '0.00',
    'therapeutic-premium': '0.00',
    cp2p: '11.52',
    cdpmq: '23.60',
    lp2p: '0.00',
    ldpmq: '0.00',
    mp2p: '0.00',
    mdpmq: '0.00',
    mrvsn: '24.90',
    bioequivalence: '',
    'brand-name': 'PRED FORTE',
    'mp-pt': 'prednisolone acetate',
    'tpuu-or-mpp-pt': 'prednisolone acetate 1% eye drops, 10 mL',
    'indication-id': '6087',
    'increase-code': '3',
    'note-ids': [
      '7606', '7607', '0',
      '0',    '0',    '0',
      '0',    '0',    '0',
      '0',    '0',    '0',
      '0',    '0',    '0'
    ],
    caution_ids: [],
    indications: {
      description: 'Uveitis',
      'misc-res-code': '0',
      'date-req': 'N',
      'text-req': 'N'
    },
    atc: 'S01BB02',
    'caution-ids': [ '0', '0', '0', '0', '0' ]
  }
}

